### ISSUE TITLE
Down All Posts From User Error

### ISSUE THREAD

**Issue by jun845** [e43b/Kemono-and-Coomer-Downloader#1]
Hello, when try to download all posts from a user I get this error. Sorry I don't know much about this stuff

Traceback (most recent call last):
  File "C:\Users\Alex\Downloads\Kemono-and-Coomer-Downloader-main\Kemono-and-Coomer-Downloader-main\codeen\code\profile.py", line 204, in <module>
    if profile_config['ambos']:
KeyError: 'ambos'

**Comment by e43b** [comment]
Hello, thank you for your report, I have corrected it here. The error was due to the translation of the program into English, some of the variables were in another language which caused the error, it should work properly now. If you could give the project a "star" it would help me a lot.
