### ISSUE TITLE
Under the post dont save video link

### ISSUE THREAD

**Issue by emilsvfx** [e43b/Kemono-and-Coomer-Downloader#10]
Under Post there is privete youtube links but it won't save it

**Comment by e43b** [comment]
> Under Post there is privete youtube links but it won't save it

Could you explain what the error is? If you prefer, you can send it to me on discord https://discord.gg/FgEUrS8f

Also send me the link to the post that found the error

**Comment by e43b** [comment]
That's something I didn't know existed. Unfortunately, it's not possible to develop a script without more examples. If you are a user and have found a profile or post that uses this, for example, https://kemono.su/patreon/user/7317358/post/82293319, please send it via Discord: https://discord.gg/CsBMMXBz7t
