### ISSUE TITLE
Is it possible to keep the original file names of the images?

### ISSUE THREAD

**Issue by QionghuaGit** [e43b/Kemono-and-Coomer-Downloader#12]
It's very difficult to organize them the way they are now, as there are many files with the same name.
![image](https://github.com/user-attachments/assets/3ea8aee4-1a70-4e98-a1de-8c1f10792c78)

**Comment by e43b** [comment]
Thanks for the feedback, I'll do it differently for the next update, get in touch on discord for more information: https://discord.gg/CsBMMXBz7t

**Comment by e43b** [comment]
Project, updated
