### ISSUE TITLE
line 50, in get_author_platform_info     author_content = author_meta_tag["content"]                      ~~~~~~~~~~~~~~~^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Harri1703** [e43b/Kemono-and-Coomer-Downloader#13]

**Comment by e43b** [comment]
The tool is experiencing some problems due to some changes on the site, I am already working on a new update with fixes for the current problems, enter the discord for more updates or suggestions: https://discord.gg/CsBMMXBz7t

**Comment by e43b** [comment]
Project, updated
