### ISSUE TITLE
Broken downloader

### ISSUE THREAD

**Issue by ikumi90s** [e43b/Kemono-and-Coomer-Downloader#14]
The downloader does not work on my side.

After I tried to post a URL on the bulk download then option 1 for all

it just promts 

> "Information for 0 posts saved and content downloaded successfully!"

it seems to be it does not download anything.
same with single post download this error appearing.

> Traceback (most recent call last):
>   File "C:\Users\my-pc-boi\Desktop\Kemono-and-Coomer-Downloader\codeen\code\post.py", line 216, in <module>
>     baixar_conteudo(url)
>   File "C:\Users\my-pc-boi\Desktop\Kemono-and-Coomer-Downloader\codeen\code\post.py", line 57, in baixar_conteudo
>     author_content = author_meta_tag["content"]
> TypeError: 'NoneType' object is not subscriptable

**Comment by KaanAlper** [comment]
any solvation?

**Comment by e43b** [comment]
@ikumi90s @Hekkun The tool is experiencing some problems due to some changes on the site, I am already working on a new update with fixes for the current problems, enter the discord for more updates or suggestions: https://discord.gg/CsBMMXBz7t

**Comment by Hekkun** [comment]
Thank you, sir!

**Comment by e43b** [comment]
Project, updated
