### ISSUE TITLE
Error in a particular post

### ISSUE THREAD

**Issue by rusantiman** [e43b/Kemono-and-Coomer-Downloader#16]
I can download other people's posts successfully.
I used the version you updated today.

Error in the following post
https://kemono.su/patreon/user/38565913/post/116559854

--- Processing link: https://kemono.su/patreon/user/38565913/post/116559854 ---
❌ Error processing link https://kemono.su/patreon/user/38565913/post/116559854: [WinError 3] The system cannot find the path specified: 'kemono\\Naon / 繝翫が繝ｳ-patreon-38565913'
Traceback (most recent call last):
  File "C:\app\KemonoDownloader\codeen\codes\kcposts.py", line 350, in main
    ensure_directory(user_folder)
  File "C:\app\KemonoDownloader\codeen\codes\kcposts.py", line 36, in ensure_directory
    os.makedirs(path)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'kemono\\Naon / 繝翫が繝ｳ-patreon-38565913'

Press Enter to continue...

I would be happy if you could correct this.

**Comment by rusantiman** [comment]
I have modified kcposts.py and now it is possible to download.
I have modified it to remove or replace characters in the file name that are not allowed by Windows.
However, there are some garbled characters, but it is OK because it is possible to download.

**Comment by e43b** [comment]
Thanks for your report, I analyzed it here and saw that the problem was in the profile name ”
Naon / ナオン” which had a ‘/’ So I modified the script to remove them replaced by ‘_’ now both ways will work, again thanks for the report and use the tool
