### ISSUE TITLE
Issue with Python

### ISSUE THREAD

**Issue by Kushimitama900** [e43b/Kemono-and-Coomer-Downloader#2]
sorry im totally new to this stuff,
i installed Python but when i try to run main.py (codeen), the program says Python not found and i cant download anything

**Comment by e43b** [comment]
What is your operating system? windows, linux mac? 64-bit or 32-bit?

**Comment by Kushimitama900** [comment]
window 64

**Comment by e43b** [comment]
Try installing this one https://www.python.org/ftp/python/3.12.4/python-3.12.4-amd64.exe just click on the link and install it

**Comment by Kushimitama900** [comment]
that was the file i installed earlier.
btw, i did again the installation with your link but the results was the same,
also i dont know if its normal but everytime i open the main.py, it asks me if i want to download the libraries.

**Comment by e43b** [comment]
Ah yes, so it's working correctly, the libraries are not python but additional extensions, just install them and the script will work correctly.

**Comment by Kushimitama900** [comment]
i wrote "y" but the installation didnt start apparently. it just goes on the next screen where i have to choose single download, artist download ecc..

**Comment by e43b** [comment]
That's right, it's not saved in the console that something has been downloaded, but if the home appears it means that it has been installed correctly, just use it now

**Comment by Kushimitama900** [comment]
it doesnt work, do i have to use python for something? or i just need it to be installed?
even this time it asked me again for the libraries, i answered "y" but same error popped up

**Comment by e43b** [comment]
Can you send me a screenshot of the specific error?

**Comment by Kushimitama900** [comment]
![Immagine1](https://github.com/e43b/Kemono-and-Coomer-Downloader/assets/173550576/656395f9-3d92-40e4-a32e-a32ed35da4d8)
![Immagine](https://github.com/e43b/Kemono-and-Coomer-Downloader/assets/173550576/5dafce8c-0807-45a5-94fd-ab4b2c4b4263)

**Comment by e43b** [comment]
That's strange, try going to "Add or Remove Programs" look for python uninstall it, then restart the pc and try installing it again, a different version

**Comment by e43b** [comment]
If you still can't make it, join the discord https://discord.gg/Q6nQ3vsWTF it's easier to chat there

**Comment by Kushimitama900** [comment]
now it's working, i installed the prev version of python and now its ok. thank you very much

**Comment by e43b** [comment]
Good man, thanks for using the project, if you have any other questions just let me know, I would also appreciate it if you could put a star on the project

**Comment by e43b** [comment]
Thanks

**Comment by Kushimitama900** [comment]
hello, sorry if for bothering you again, i noticed that the when i try to download ALL the content of an artist, the time is very long and if oftenthe process is interrupted midway. There is a way for continuing the download of the posts left?

**Comment by e43b** [comment]
> hello, sorry if for bothering you again, i noticed that the when i try to download ALL the content of an artist, the time is very long and if oftenthe process is interrupted midway. There is a way for continuing the download of the posts left?

Hello, it’s not a bother. Recently, I added a new feature to the project in the Manual Download section. You can check it out in the documentation here: https://github.com/e43b/Kemono-and-Coomer-Downloader?tab=readme-ov-file#option-2-download-posts-from-a-json-file.

You can create the JSON file with the missing part as indicated in the documentation. Then, this generated file can be used to download posts manually.

I think this works well for this purpose

**Comment by Kushimitama900** [comment]
im sorry im a total noob in this kind of things.
what does it mean to run the command "python links.py" in the directory?

**Comment by e43b** [comment]
> im sorry im a total noob in this kind of things. what does it mean to run the command "python links.py" in the directory?

You need to clone the repository again, thus downloading the new updated version

**Comment by e43b** [comment]
> im sorry im a total noob in this kind of things.
> what does it mean to run the command "python links.py" in the directory?

This script was developed to retrieve links from posts on specific pages and save them in a json file, as described in the documentation. This script simply extracts links in a way that is quick for the user to use
