### ISSUE TITLE
Execution failure error after 'python' output

### ISSUE THREAD

**Issue by legendkey** [e43b/Kemono-and-Coomer-Downloader#3]
I've tried adding a pass as an system's environment variable, but that hasn't fixed it either. Is there a fix?
![image](https://github.com/user-attachments/assets/775ce55a-088e-4a7d-8462-aa397cf4fb45)

**Comment by e43b** [comment]
Hi, can you please send me the time when you're having the problem, whether it's when you insert the link to the post or something else, I've tested it here and it doesn't seem to be an error

**Comment by e43b** [comment]
Oh, no problem, if you could leave a star in the repository I'd appreciate it, any other problems just open it again or send a message on the discord server
