### ISSUE TITLE
ERROR author_content = author_meta_tag["content"]

### ISSUE THREAD

**Issue by khacthiennguyen** [e43b/Kemono-and-Coomer-Downloader#8]
An error occurs when I try to Download posts from a JSON file. I think the structure of the [content] tag has changed on the website. I have tried loading and inspecting several user URLs, but the following error still occurs. Could you please review the issue?
![image](https://github.com/user-attachments/assets/e2166cb2-d6d2-4a0d-8bfd-57d7383fb696)

**Comment by khacthiennguyen** [comment]
Even though I tried each step and with the id in your example, the result is still the same:
![image](https://github.com/user-attachments/assets/f6b09547-6052-43c0-999e-7a5fb51688f9)

**Comment by e43b** [comment]
> An error occurs when I try to Download posts from a JSON file. I think the structure of the [content] tag has changed on the website. I have tried loading and inspecting several user URLs, but the following error still occurs. Could you please review the issue? ![image](https://private-user-images.githubusercontent.com/97331675/360877878-e2166cb2-d6d2-4a0d-8bfd-57d7383fb696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDc3OTIsIm5iZiI6MTcyNDQwNzQ5MiwicGF0aCI6Ii85NzMzMTY3NS8zNjA4Nzc4NzgtZTIxNjZjYjItZDZkMi00YTBkLThiZmQtNTdkNzM4M2ZiNjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEwMDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMThhNmQ1MzQ3NzkzNWRlM2M0ZGZhYTVkNDA4NDEwZTk0Yjk3NTA0NzA1YWFjYWE2ZWM0Zjg0ZDU1ODk5YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7iQWqNyABmTgSpQ5hTdoV41YXtfMLlFnTZyLpQ0XSCM)

Send the profile or the link of the posts you tried to download

**Comment by khacthiennguyen** [comment]
> > An error occurs when I try to Download posts from a JSON file. I think the structure of the [content] tag has changed on the website. I have tried loading and inspecting several user URLs, but the following error still occurs. Could you please review the issue? ![image](https://private-user-images.githubusercontent.com/97331675/360877878-e2166cb2-d6d2-4a0d-8bfd-57d7383fb696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDc3OTIsIm5iZiI6MTcyNDQwNzQ5MiwicGF0aCI6Ii85NzMzMTY3NS8zNjA4Nzc4NzgtZTIxNjZjYjItZDZkMi00YTBkLThiZmQtNTdkNzM4M2ZiNjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEwMDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMThhNmQ1MzQ3NzkzNWRlM2M0ZGZhYTVkNDA4NDEwZTk0Yjk3NTA0NzA1YWFjYWE2ZWM0Zjg0ZDU1ODk5YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7iQWqNyABmTgSpQ5hTdoV41YXtfMLlFnTZyLpQ0XSCM)
> 
> Send the profile or the link of the posts you tried to download

I try with https://coomer.su/onlyfans/user/breeflaa
![image](https://github.com/user-attachments/assets/a7a4b8cb-6503-4b57-b1f5-1a9a781601f7)

**Comment by e43b** [comment]
![image](https://github.com/user-attachments/assets/e0a9dc24-4919-46ae-85f9-878770944e0f)
I tested with the link https://coomer.su/fansly/user/285310079517863936 and also https://coomer.su/onlyfans/user/breeflaa, and the error did not occur. All the libraries are installed. Did you change anything? Try cloning the repository again; it might resolve the issue

**Comment by khacthiennguyen** [comment]
I added a few code snippets to test how soup returns html content. 
The result is not a program error but the browser returning a DDoS-Guard website
![image](https://github.com/user-attachments/assets/14068228-33e2-4268-aa34-4eea7411860c)

How can you download in bulk without attracting suspicion? Any tips? Thank you

**Comment by e43b** [comment]
> I added a few code snippets to test how soup returns html content. The result is not a program error but the browser returning a DDoS-Guard website ![image](https://private-user-images.githubusercontent.com/97331675/360939454-14068228-33e2-4268-aa34-4eea7411860c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTk2ODcsIm5iZiI6MTcyNDQxOTM4NywicGF0aCI6Ii85NzMzMTY3NS8zNjA5Mzk0NTQtMTQwNjgyMjgtMzNlMi00MjY4LWFhMzQtNGVlYTc0MTE4NjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEzMjMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMzVkMzcxOGIxYTkxNDE3YWM0ODhjMmU4MzhhYTk0NzM2N2FlYTVmYWIzYzExYjUzYTFmZGM2N2RjOGRlNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ePH3B9Jk5gi4Xu81w1VY1dALG1HWUCzN4Xt9XwSUbDs)
> 
> How can you download in bulk without attracting suspicion? Any tips? Thank you

Well, I've never had problems with that. What country are you in? Sometimes the owner may have set specific restrictions for certain countries. I’ve talked to a lot of people, for example, in France, some sites are blocked for some reason. One solution could be using a VPN on your PC; that might help, or you can use the tool on Replit. I've never had issues running my tests there. If you have Discord, we can chat more there: https://discord.gg/EYMadby7

**Comment by khacthiennguyen** [comment]
Thank you for tips, 
I tried fake ip roaming to another country and the program ran successfully. Hope someone reads this if having the same problem
